#!/bin/bash

### APT + FZF
# install multiple packages at once
# mnemonic [A]pt [I]nstall [P]ackage

inst=$(parse_packages $(apt list | eval "fzf ${FZF_DEFAULT_OPTS} -m --header='[apt:install]'"))

if [[ -n $inst ]]; then
  sudo apt install $inst
fi
