#!/bin/bash
#
# http://github.com/mitchweaver/bin
#
# play a video on the root window
#

[ -n "$1" ] || exit 1

pkill -9 xwinwrap


get_xwin () { 
  echo "xwinwrap -g 1920x1080+$1+0 -ni -fdt -un -s -sp -st -b -nf -ov -- "
}

st="st -w WID -g=192x57 -e $1"

# shellcheck disable=SC2086
$(get_xwin 0) $st > /dev/null 2>&1 &
echo -n $! > "${HOME}/.cache/mpvbg.pid"

# shellcheck disable=SC2086
$(get_xwin 1920) $st > /dev/null 2>&1 &
echo -n $! >> "${HOME}/.cache/mpvbg.pid"
