#!/bin/bash

caps_lock_on=0
sym_lock_on=0

if [ "on" = "$(xset q | grep -m 1 "Caps Lock" | grep -o ':   \w\+' |
  grep -o '\w\+')" ]; then
  caps_lock_on=1
fi

if [ -f /tmp/keyboard_info/sym_toggle_activated ]; then
  sym_lock_on=1
fi

if [ $caps_lock_on -eq 1 ] && [ $sym_lock_on -eq 1 ]; then
  echo "CAPS-SYM"
  echo "#ff0000"
elif [ $caps_lock_on -eq 1 ]; then
  echo "CAPSLOCK"
  echo "#ff0000"
elif [ $sym_lock_on -eq 1 ]; then
  echo "SYMLOCK"
  echo "#d79921"
fi
