#!/bin/bash

battery_life_over_threshold=true
while true; do
  BATTINFO=$(acpi -b | grep -Eo 'Discharging.*remaining')
  if [[ ! -z $BATTINFO && $(echo "$BATTINFO" | cut -f 2 -d " " | grep -Eo "[0-9]+") -lt 15 ]]; then
    if [ "$battery_life_over_threshold" = true ]; then
      notify-send -u critical -t 10000 "LOW BATTERY" "$(echo "$BATTINFO" | grep -Eo '[0-9]+%.*[0-9]')"
    fi

    battery_life_over_threshold=false
  else
    if [[ ! -z $BATTINFO && $(echo "$BATTINFO" | cut -f 2 -d " " | grep -Eo "[0-9]+") -gt 16 ]]; then
      battery_life_over_threshold=true
    fi
  fi
  sleep 10
done
