#!/bin/bash

###mgitstatus + FZF
# cd to git repos using mgitstatus
# intention is that this is called using `cd $(mgs_path ARGS)` or
#mgs() {
#  cd $(mgs_path $@)
#}
#is defined in the .zshrc/.bashrc

file_path=$(mgitstatus "$@" |
  eval "fzf ${FZF_DEFAULT_OPTS} --header='[mgitstatus]' --preview 'parse_cd_status {}'")

if [[ -n $file_path ]]; then
  parse_cd_status "$file_path"
else
  exit 1
fi
