#!/bin/bash

if [ -t 1 ] && [ -n "${NVIM_LISTEN_ADDRESS+x}" ]; then
  nvr -c "call FloatingOverWindow('$PWD/$1')"
else
  if identify "$1" &>/dev/null; then
    timg "$@"
  elif [[ -d $1 ]]; then
    exa --color=always -Ta "$@"
  elif [[ -f $1 ]]; then
    bat --style=numbers,changes --color always "$@"
  else
    echo "No preview"
    exit 1
  fi
fi
