#!/bin/bash

if identify $1 &> /dev/null; then 
    timg $1
elif [[ -d $1 ]]; then
    exa --color=always -1 $1
elif [[ -f $1 ]]; then
    bat --style=numbers,changes --color always $1
else
    echo "No preview"
    exit 1
fi
