#!/bin/bash

[ -n "$1" ] || exit 1

pkill -9 xwinwrap

get_xwin() {
  echo "xwinwrap -g 1920x1080+$1+0 -ni -fdt -un -s -sp -st -b -nf -ov -- "
}

# shellcheck disable=SC2086
$(get_xwin 0) $1 >/dev/null 2>&1 &
echo -n $! >"${HOME}/.cache/mpvbg.pid"

# shellcheck disable=SC2086
$(get_xwin 1920) $1 >/dev/null 2>&1 &
echo -n $! >>"${HOME}/.cache/mpvbg.pid"
