#!/bin/sh

# Authors:
# - Moritz Warning <moritzwarning@web.de> (2016)
# - Zhong Jianxin <azuwis@gmail.com> (2014)
#
# See file LICENSE at the project root directory for license information.
#
# i3status.conf should contain:
# general {
#   output_format = i3bar
# }
#
# i3 config looks like this:
# bar {
#   status_command exec /usr/share/doc/i3status/contrib/net-speed.sh
# }
#
# Single interface:
# ifaces="eth0"
#
# Multiple interfaces:
# ifaces="eth0 wlan0"
#

caps_lock=""

update_caps_lock() {
  if [ "on" = $(xset q | grep -m 1 "Caps Lock" | grep -o ':   \w\+' | grep -o '\w\+') ]
  then 
    caps_lock="{\"name\":\"capslock\",\"color\":\"#ff0000\",\"markup\":\"none\",\"full_text\":\"CAPSLOCK\"},"
  else
    caps_lock=""
  fi
}
sym_lock=""

update_sym_lock() {
  if [ -f /tmp/keyboard_info/sym_toggle_activated ]
  then 
    sym_lock="{\"name\":\"symlock\",\"color\":\"#d79921\",\"markup\":\"none\",\"full_text\":\"SYMLOCK\"},"
  else
    sym_lock=""
  fi
}

py3status | (read line && echo "$line" && read line && echo "$line" && read line && echo "$line" && while :
do
  read line
  update_caps_lock
  update_sym_lock
  echo ",[{\"full_text\":\"\" },${sym_lock}${caps_lock}${line#,\[}" || exit 1
done)
